### ISSUE TITLE
Removing lib{flac | vorbis | ogg} dependencies?

### ISSUE THREAD

**Issue by hbredin** [conda-forge/libsndfile-feedstock#2]
Are `libflac`, `libvorbis`, and `libogg` really necessary?
It apparently causes issues on older systems with `GLIBC < 2.7`.
Would it be OK to remove those dependencies?

**Comment by thomasfillon** [comment]
These libraries are optional I think and are only require if you need to read Flac, Ogg Vorbis and related audio formats.

I have to check how to build several version (with or without these libraries).

**Comment by thomasfillon** [comment]
@hbredin Do you have error log for this issue with glibC < 2.7 ?
I'm surprised that no other package (like numpy, scipy) are concern with glibc version.

**Comment by hbredin** [comment]
```bash
$ conda create -n glibc-bug python=3.6
$ source activate glibc-bug
$ conda install -c conda-forge yaafe
$ yaafe-engine
ERROR: cannot load yaafe component library "libyaafe-io.so" !
/lib64/libc.so.6: version `GLIBC_2.7' not found (required by [REDACTED]/anaconda2/envs/glibc-bug-yaafe/bin/../lib/././libmpg123.so.0)
```

Here it complains about `libmpg123` but the same error happens with `libflac`, `libvorbis`, and `libogg`.

For completeness:

```bash
$ uname -a
Linux [REDACTED] 2.6.18-164.6.1.el5 #1 SMP Tue Nov 3 16:12:36 EST 2009 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by CodesWithWolves** [comment]
The top-level CMakeLists.txt provides an option to remove the dependencies on these three external libraries:  
**libsndfile/CMakeLists.txt**: `option (DISABLE_EXTERNAL_LIBS "Disable use of FLAC, Ogg and Vorbis" OFF)`

Because it's default `OFF`, all that's needed is to turn it on in the cmake step of the build process by running:  
`cmake . -DDISABLE_EXTERNAL_LIBS=ON`

**Comment by mgeier** [comment]
Please don't remove those dependencies!

Reading/writing FLAC/OGG files is a very important feature.

If there are problems with the `*.so` files, would it be feasible to statically link `libflac`, `libogg` and `libvorbis` into `libsndfile`?

For reference, I've done this (for macOS and Windows) here: https://github.com/bastibe/libsndfile-binaries.

**Comment by faroit** [comment]
I installed the `conda-forge/osx-64::libsndfile-1.0.28-h0a44026_1000` which, I guess, was built using this recipe. When trying to read a flac file, I get an error stating that `This version of libsndfile was compiled without FLAC support`. 

Has FLAC support already been removed for the OSX version?

**Comment by lminer** [comment]
Being able to read flac is pretty useful, it's a shame this has been disabled.

**Comment by wolfv** [comment]
I don't think this makes sense, and we have a fairly well specified backward compatbility range with glibc. GLIBC < 2.7 is too old I think :)

**Comment by lminer** [comment]
@wolfv so does that mean flac support is in fact still enabled?

**Comment by wolfv** [comment]
it is enabled _again_. there was an issue on the latest flac build on conda-forge that didn't include the correct `pkgconfig` files. 
And now libsndfile is recompiled and released as well so FLAC support is back in.

**Comment by wolfv** [comment]
From the build log on Linux:

![image](https://user-images.githubusercontent.com/885054/100674222-1ca1a080-3365-11eb-825c-aaf622efc6e1.png)

**Comment by zh794390558** [comment]
need install `pkg-config libflac-dev libogg-dev libvorbis-dev` before compile libsndfile

**Comment by wolfv** [comment]
This is concerning conda packages and you can get all dependencies through conda

**Comment by mgrachten** [comment]
With 1.0.31 (build `conda-forge/osx-64::libsndfile-1.0.31-h046ec9c_0`) again there is no flac support :-(

**Comment by wolfv** [comment]
@mgrachten can you open a seperate issue?
