### ISSUE TITLE
Restart failed PPC build for #26

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/libsndfile-feedstock#28]
PPC builds for https://github.com/conda-forge/libsndfile-feedstock/pull/26 (both 6b4d7f4a225edab304a8ce32a2c249f0d52935fa & 682c2519891c8b304e8d8f517e4af03268c83db1) failed, leading to resolver errors in https://github.com/conda-forge/sdl2_mixer-feedstock/pull/13, because https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3901 hasn't run through yet.

Could someone restart that build please?

**Comment by wolfv** [comment]
I pressed a button just now to do that

**Comment by h-vetinari** [comment]
Thanks a lot. But of course it ran into the token issue 😑

**Comment by h-vetinari** [comment]
Not relevant anymore now that we built for new libsndfile
